import { expect, test } from "@playwright/test";
import { createClient } from "@supabase/supabase-js";
import fixture from "../../lib/stock-research/fixtures/aapl.json";

test("unauthenticated users cannot access the lab or MCP",async({page,request})=>{await page.goto("/challenges/source-grounded-stock-research/v/1.0.0");await expect(page).toHaveURL(/\/login\?next=/);const response=await request.post("/api/mcp/stock-research",{data:{jsonrpc:"2.0",id:1,method:"stock_research.status",params:{runId:"f67b0603-94dd-4103-a495-2e694def9ad2"}}});expect(response.status()).toBe(401)});

test("learner reviews, approves, and reads a replayed paper-trade bundle",async({page})=>{
 const email=process.env.E2E_USER_EMAIL,password=process.env.E2E_USER_PASSWORD,url=process.env.NEXT_PUBLIC_SUPABASE_URL,service=process.env.SUPABASE_SERVICE_ROLE_KEY;
 if(!email||!password||!url||!service)throw new Error("E2E_USER_EMAIL, E2E_USER_PASSWORD, NEXT_PUBLIC_SUPABASE_URL, and SUPABASE_SERVICE_ROLE_KEY are required");
 const admin=createClient(url,service,{auth:{persistSession:false}});const users=await admin.auth.admin.listUsers();const user=users.data.users.find(candidate=>candidate.email===email);if(!user)throw new Error("E2E user not found");
 const inserted=await (admin.from("stock_research_run" as never) as unknown as {insert:(value:object)=>{select:(columns:string)=>{single:()=>Promise<{data:{id:string}|null;error:{message:string}|null}>}}}).insert({user_id:user.id,tenant_id:user.id,ticker:"AAPL",as_of:fixture.asOf,challenge_version:"1.0.0"}).select("id").single();if(inserted.error||!inserted.data)throw new Error(inserted.error?.message??"run insert failed");
 const runId=inserted.data.id;const claim=await (admin.rpc as unknown as (name:string,args:object)=>Promise<{error:{message:string}|null}>)("stock_research_claim_run",{p_run_id:runId,p_version:"1.0.0"});if(claim.error)throw new Error(claim.error.message);const complete=await (admin.rpc as unknown as (name:string,args:object)=>Promise<{error:{message:string}|null}>)("stock_research_complete_run",{p_run_id:runId,p_bundle:fixture});if(complete.error)throw new Error(complete.error.message);
 try{await page.goto("/login");await page.getByLabel(/email/i).fill(email);await page.getByLabel(/password/i).fill(password);await page.getByRole("button",{name:/sign in/i}).click();await page.goto("/challenges/source-grounded-stock-research/v/1.0.0");await expect(page.getByRole("heading",{name:"Source-grounded stock research lab"})).toBeVisible();await page.getByRole("button",{name:"Approve immutable bundle"}).click();await expect(page.getByText("approved")).toBeVisible();const response=await page.request.post("/api/mcp/stock-research",{data:{jsonrpc:"2.0",id:1,method:"stock_research.approved_bundle",params:{runId}}});expect(response.status()).toBe(200);expect((await response.json()).result.paperTrade.simulationOnly).toBe(true)}finally{await (admin.from("stock_research_run" as never) as unknown as {delete:()=>{eq:(column:string,value:string)=>Promise<unknown>}}).delete().eq("id",runId)}
});
