/* eslint-disable @typescript-eslint/no-explicit-any */
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
const url=process.env.NEXT_PUBLIC_SUPABASE_URL??"http://127.0.0.1:54321";
const anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const service=process.env.SUPABASE_SERVICE_ROLE_KEY;
if(!anon||!service) throw new Error("Local Supabase anon and service-role keys are required");
const admin=createClient(url,service,{auth:{persistSession:false}});let first:SupabaseClient,second:SupabaseClient;const ids:string[]=[];
const legacyTables=["challenge","attempt"] as const;const before:Record<string,number|null>={};
beforeAll(async()=>{for(const table of legacyTables){const {count}=await admin.from(table).select("*",{count:"exact",head:true});before[table]=count}const password="Mission001-test-password!";for(const n of [1,2]){const email=`mission001-${crypto.randomUUID()}-${n}@example.test`;const {data,error}=await admin.auth.admin.createUser({email,password,email_confirm:true});if(error||!data.user)throw error;ids.push(data.user.id);const client=createClient(url,anon,{auth:{persistSession:false}});const signed=await client.auth.signInWithPassword({email,password});if(signed.error)throw signed.error;if(n===1)first=client;else second=client;}});
afterAll(async()=>{for(const id of ids)await admin.auth.admin.deleteUser(id)});
describe("stock research tenant boundaries",()=>{it("isolates two owners and leaves legacy tables unchanged",async()=>{const inserted=await (first.from("stock_research_run" as any) as any).insert({user_id:ids[0],tenant_id:ids[0],ticker:"AAPL",as_of:"2024-11-01T23:59:59Z",challenge_version:"1.0.0"}).select("id").single();expect(inserted.error).toBeNull();const other=await (second.from("stock_research_run" as any) as any).select("id").eq("id",inserted.data.id);expect(other.data).toEqual([]);for(const table of legacyTables){const {count}=await admin.from(table).select("*",{count:"exact",head:true});expect(count).toBe(before[table])}});it("denies cross-tenant insertion and premature decisions",async()=>{const bad=await (first.from("stock_research_run" as any) as any).insert({user_id:ids[0],tenant_id:ids[1],ticker:"AAPL",as_of:"2024-11-01T23:59:59Z",challenge_version:"1.0.0"});expect(bad.error).not.toBeNull();const run=await (first.from("stock_research_run" as any) as any).select("id").limit(1).single();const decision=await (first.rpc as any)("stock_research_decide_run",{p_run_id:run.data.id,p_decision:"approved"});expect(decision.error).not.toBeNull()})});
